### ISSUE TITLE
Copying equipment from catalogues does not seem to work if the person does not own all the parameters

### ISSUE THREAD

**Issue by adrianchivu** [RHEAGROUP/COMET-IME-Community-Edition#768]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of the CDP4-IME
- [X] I have searched [open](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues) and [closed](https://github.com/RHEAGROUP/CDP4-IME-Community-Edition/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
In the IME Tool the Domain Experts should be able to copy equipment between models even if they do not own all the parameters.

**Comment by adrianchivu** [comment]
![image](https://user-images.githubusercontent.com/47980674/110121571-3967cd00-7dc7-11eb-88d2-4a6f6427284b.png)

**Comment by samatrhea** [comment]
This is possible provided the correct SHFT+CTRL drag combinations are used.

  - COPY: The Element Definition is copied, including the contained Element Usages and Parameters. The ownership in the target model is set to the Active Domain. The values are set to the default “-“.
  - CTRL COPY: The Element Definition is copied, including the contained Element Usages and Parameters, the ownership in the target model is set to the Active Domain. The values are set to values as defined in the source Model.
  - SHIFT COPY: The Element Definition is copied, including the contained Element Usages and Parameters. The ownership in the target model is set to the ownership as defined in the source model. The values are set to the default “-“.
  - CTRL+ SHIFT COPY: The Element Definition is copied, including the contained Element Usages and Parameters. The ownership in the target model is set to the ownership as defined in the source model. The values are set to values as defined in the source Model.

**Comment by samatrhea** [comment]
@adrianchivu: when you create a ticket, can you please (as is in the issue template) the version number of the server and of the desktop app?

**Comment by lxatrhea** [comment]
Discuss this with Johan and Marcel.

**Comment by JVennekens** [comment]
![image](https://user-images.githubusercontent.com/81681671/149365138-a94cecc7-5466-4572-b0ad-daed29199aae.png)

This error was encountered when our expert used the ctrl-shift-copy on an element definition with parameters with different owners. The person copying was not a model administrator.

**Comment by nlmave** [comment]
We did some more testing - to exclude the role of Citrix application delivery services. Tested with IME 9.0.1 and server 7.0.3

DRAG works fine both locally and on Citrix.   

CTRL+SHIFT+DRAG works fine both locally and on Citrix.

CTRL+DRAG does not perform any function locally or on Citrix. 

Do note that these steps were performed in the role as model admin. 

The error message provided by the end-user listed in previous comment therefore seems to be a permissions based issue on the server side, so we expect this not related to Citrix.

**Comment by lxatrhea** [comment]
@nlmave 
We found and fixed a bug that has to do with reading model data and Person.DefaultDomain. In an edge-case the user was able to get data for a DomainOfExpertise that is not linked to Participant information.
We fixed that in the IME.
We think this was the first part of the problem.
The second part is that the (DevExpress) TreeList component's development through the years, has created a compatibility issue regarding the CTRL-COPY option we use when copying Elements from one model to the other.
Currently CTRL-CLICK toggle's the visual (multi)selection-state in the TreeList at MouseDown level. 

The natural way in which we, as users, want to perform the drag/drop action necessary to copy the element would be:
CTRL -> CLICK -> MOVE -> DROP

However, due to the TreeList's MultiSelect implementation, the first part (CTRL + CLICK together) (de)selects the row and the MOVE/DRAG action will not start as expected. Resulting in the user concluding that the CTRL+COPY action doesn't work at all.

The solution for now is that the order when dragging an element to another model should be:
CLICK -> MOVE -> CTRL -> DROP

We are planning to change this behavior as it is now, is far from obvious.
We want to implement a ContextMenu that will popup automatically when the user drops the Element and it will contain all options that the user can perform (Current CTRL and/or SHIFT implementation) in a textual form. We hope that this is more intuitive and it is a way to maintain the MultiSelect  options in the TreeList together with the necessary flexibility of copying elements between models.

**Comment by samatrhea** [comment]
@JVennekens this is the strategy that we are going to follow. We will have one standard operation, and next to that a SHFT-DRAG to ask for a dialog to specify which kind op copy is being requested. In that way you do not have to remember the different key combinations. We also don;t want people to have to always choose. So the default is: "copy the ElementDefinition as-is to the target model, keeping ownership and values".

**Comment by MartinFijneman** [comment]
preliminary testing done on the [fix for default domain](https://github.com/RHEAGROUP/COMET-IME-Community-Edition/commit/11e96934ad5ff425f418dcbba55386a901afe24b)
working for parameters themselves now. Did notice issue with subscriptions being created for non-active domain in target model, reported as new issue #1038

**Comment by nlmave** [comment]
The 9.1 release of COMET IME does not resolve the core of the problem - the ability to copy parameters that are not owned by the person performing the copy. We have libraries of generic equipments that contain a parameters owned by multiple domains (each parameter is of course owned by a single DoE, but not all parameters are owned by the same DoE in this case). It MUST be possible to copy these generic definitions WITHOUT the need for admin privileges. At the moment none of our generic equipment definitions can be reused, as they (for example) all contain a parameter to link to the 3D location, which is owned by the configuration DoE. A technical solution for this must be found as soon as possible.

**Comment by samatrhea** [comment]
Sounds like this needs to be fixed server-side, we get right on it!

**Comment by nlmave** [comment]
Let have a short meeting to get the issue really clear. There are quite a few subtle interactions between data and acces right model to consider.

**Comment by alexatrhea** [comment]
WebServices PR https://github.com/RHEAGROUP/COMET-WebServices-Community-Edition/pull/259
